FROM rust:1.86-slim AS builder

WORKDIR /app
COPY Cargo.toml .
COPY src/rust ./src
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/ai-tauron /usr/local/bin/
CMD ["ai-tauron"]
